service: nodejs-example-serverless

provider:
  name: aws
  runtime: nodejs14
  stage: dev
  region: eu-west-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
